package org.citydb.ade.quality.schema;

public enum ADESequence {
    ERROR_SEQ,
    ERROR_SEQ_1,
    CHECKING_SEQ,
    EDGE_SEQ,
    EDGELIST_SEQ,
    FEATURESTATISTIC_SEQ,
    FILTER_SEQ,
    POLYGONIDLIST_SEQ,
    GLOBALPARAMETERS_SEQ,
    PARAMETER_SEQ,
    REQUIREMENT_SEQ,
    STATISTICS_SEQ,
    VALIDATIONPLAN_SEQ,
    VALIDATIONRESULT_SEQ
}
